### ISSUE TITLE
Scrape the crime datas from Government

### ISSUE THREAD

**Issue by CS-Brandon** [ChicoState/StaySafe#4]
Scraping reliable live crime datas from Government. Use FBI API, and javascript for scraping.

**Comment by evanalba** [comment]
FBI Developer info page: https://www.justice.gov/developer 
FBI Crime Data API: https://cde.ucr.cjis.gov/LATEST/webapp/#/pages/docApi 
Note: We got to sign up for an API asap.

**Comment by CS-Brandon** [comment]
Out of all the programs, it seems that the **Uniform Crime Reporting (UCR) program**, is best suited for us. It includes data reported by law enforcement agencies across the United States. This data can be organized by location, including by cities, which is crucial for our app.

It  offers two reporting formats: 
Summary Reporting System (SRS): Provides aggregated counts of reported crime offenses by location.
National Incident Based Reporting System (NIBRS): Provides a detailed incident-based view, including the time of day, demographics of offenders/victims, and specific incident details.
